export const dataTeams = [
    {
        id: 1,
        name: "Los Angeles Lakers",
        conference: "Western Conference",
        logo: "link_para_logo_lakers",
    },
    {
        id: 2,
        name: "Golden State Warriors",
        conference: "Western Conference",
        logo: "link_para_logo_warriors",
    },
    {
        id: 3,
        name: "Los Angeles Clippers",
        conference: "Western Conference",
        logo: "link_para_logo_clippers",
    },
    {
        id: 4,
        name: "Phoenix Suns",
        conference: "Western Conference",
        logo: "link_para_logo_suns",
    },
    {
        id: 5,
        name: "Denver Nuggets",
        conference: "Western Conference",
        logo: "link_para_logo_nuggets",
    },
    {
        id: 6,
        name: "Utah Jazz",
        conference: "Western Conference",
        logo: "link_para_logo_jazz",
    },
    {
        id: 7,
        name: "Dallas Mavericks",
        conference: "Western Conference",
        logo: "link_para_logo_mavericks",
    },
    {
        id: 8,
        name: "Portland Trail Blazers",
        conference: "Western Conference",
        logo: "link_para_logo_blazers",
    },
    {
        id: 9,
        name: "Memphis Grizzlies",
        conference: "Western Conference",
        logo: "link_para_logo_grizzlies",
    },
    {
        id: 10,
        name: "San Antonio Spurs",
        conference: "Western Conference",
        logo: "link_para_logo_spurs",
    },
    {
        id: 11,
        name: "Minnesota Timberwolves",
        conference: "Western Conference",
        logo: "link_para_logo_timberwolves",
    },
    {
        id: 12,
        name: "New Orleans Pelicans",
        conference: "Western Conference",
        logo: "link_para_logo_pelicans",
    },
    {
        id: 13,
        name: "Houston Rockets",
        conference: "Western Conference",
        logo: "link_para_logo_rockets",
    },
    {
        id: 14,
        name: "Sacramento Kings",
        conference: "Western Conference",
        logo: "link_para_logo_kings",
    },
    {
        id: 15,
        name: "Oklahoma City Thunder",
        conference: "Western Conference",
        logo: "link_para_logo_thunder",
    },
    {
        id: 16,
        name: "Brooklyn Nets",
        conference: "Eastern Conference",
        logo: "link_para_logo_nets",
    },
    {
        id: 17,
        name: "Philadelphia 76ers",
        conference: "Eastern Conference",
        logo: "link_para_logo_76ers",
    },
    {
        id: 18,
        name: "Milwaukee Bucks",
        conference: "Eastern Conference",
        logo: "link_para_logo_bucks",
    },
    {
        id: 19,
        name: "Atlanta Hawks",
        conference: "Eastern Conference",
        logo: "link_para_logo_hawks",
    },
    {
        id: 20,
        name: "Miami Heat",
        conference: "Eastern Conference",
        logo: "link_para_logo_heat",
    },
    {
        id: 21,
        name: "New York Knicks",
        conference: "Eastern Conference",
        logo: "link_para_logo_knicks",
    },
    {
        id: 22,
        name: "Boston Celtics",
        conference: "Eastern Conference",
        logo: "link_para_logo_celtics",
    },
    {
        id: 23,
        name: "Charlotte Hornets",
        conference: "Eastern Conference",
        logo: "link_para_logo_hornets",
    },
    {
        id: 24,
        name: "Indiana Pacers",
        conference: "Eastern Conference",
        logo: "link_para_logo_pacers",
    },
    {
        id: 25,
        name: "Washington Wizards",
        conference: "Eastern Conference",
        logo: "link_para_logo_wizards",
    },
    {
        id: 26,
        name: "Toronto Raptors",
        conference: "Eastern Conference",
        logo: "link_para_logo_raptors",
    },
    {
        id: 27,
        name: "Chicago Bulls",
        conference: "Eastern Conference",
        logo: "link_para_logo_bulls",
    },
    {
        id: 28,
        name: "Cleveland Cavaliers",
        conference: "Eastern Conference",
        logo: "link_para_logo_cavaliers",
    },
    {
        id: 29,
        name: "Orlando Magic",
        conference: "Eastern Conference",
        logo: "link_para_logo_magic",
    },
    {
        id: 30,
        name: "Detroit Pistons",
        conference: "Eastern Conference",
        logo: "link_para_logo_pistons",
    },
];
